services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: ./brain/Dockerfile
    container_name: backend
    environment:
        - QDRANT_URL=http://qdrant:6333
    env_file:
      - .env
    depends_on:
      - qdrant
    restart: unless-stopped
    volumes:
      - ./brain/docs:/app/brain/docs

volumes:
  qdrant_storage: